### ISSUE TITLE
Snap.svg 

### ISSUE THREAD

**Issue by aysha15** [adobe-webplatform/Snap.svg#347]
Hey ,i get started with svg and i don't know how to get the Snap library  and svg in a web page 
Someone can help me please

**Comment by ian-workcircle** [comment]
First bit, have you include the snap.svg.js file as a linked local file or cdn or something ? I would start with that...eg  something like the following. 
`<script src="snap.svg.js"></script>`   if the file is local. Then test with 
`<script>
var s = Snap(800,800);
var r = s.rect(100,100,100,100);
console.log( s );
</script>`
Or you can reference an existing svg element on the page with Snap("#mySvgId"); rather than the Snap line above.

I would post what you have so far so people can help where you are going wrong, maybe post on Stackoverflow rather than here as well.

**Comment by ibrierley** [comment]
First bit, have you include the snap.svg.js file as a linked local file or cdn or something ? I would start with that...eg something like the following. 
<script src="snap.svg.js"></script> if the file is local. Then test with 
<script> var s = Snap(800,800); var r = s.rect(100,100,100,100); console.log( s ); </script>
Or you can reference an existing svg element on the page with Snap("#mySvgId"); rather than the Snap line above.

Look in your console for errors (ctrl-shift-j on chrome/firefox).

I would post what you have so far so people can help where you are going wrong, maybe post on Stackoverflow rather than here as well.

**Comment by aysha15** [comment]
Infact i did  include the snap.svg.js file as a linked local file but when u test i get nothing
Thanksc

**Comment by ibrierley** [comment]
You need to post more info, maybe include a jsfiddle of your example.

**Comment by aysha15** [comment]
shall you give me a detailed link example

**Comment by ibrierley** [comment]
Where did you include it ? I can't see it anywhere. Can you provide a link to it here ?
