### ISSUE TITLE
Clone() produces TypeError: Constructor URL requires 'new'

### ISSUE THREAD

**Issue by bakajin** [adobe-webplatform/Snap.svg#390]
Snap Snap.svg 0.4.1

When loading an external SVG and cloning it, to iterate a series of buttons for a menu. Chrome (Mac) produces the failure: 

Uncaught TypeError: Failed to construct 'URL': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

firefox:
TypeError: Constructor URL requires 'new' at line 3136
	
which is in function fixids: 

      attr[name] = URL(id);

When I make that:
      attr[name] = new URL(id);

Firebug produces
    TypeError: radialGradientSiap76j711b is not a valid URL. 

Loading and then displaying this file works as expected.

**Comment by ibrierley** [comment]
Possible to put it on a jsfiddle to test ?

**Comment by bakajin** [comment]
I have fiddled it into a working version by now. Still running into trouble though. So a fiddle might not make things clearer, however:

https://jsfiddle.net/6zsbe9we/

**Comment by bakajin** [comment]
Seeing as the before mentioned 

    Snap(g.node.cloneNode(true));

provides a workaround I am closing this issue for now

**Comment by ylerjen** [comment]
Snap.svg 0.4.x

I've encountered the same bug with either Snap0.4.1 or Snap.0.4.0. But for me the workaround doesn't work at all. As Bakajin, this happens when loading an external SVG and cloning it.

This was the buggy line :
`clone = el.clone();    //this threw : Failed to construct 'URL': Please use the 'new' operator `
So I replaced it with Bakajin's proposal :
`clone = Snap(el.node.cloneNode(true));`

But the bug's still there.
Can somebody tell me if I'm missing something or if there is really an issue about this ?
Otherwise I will have to use the 0.3.0 version.

Thanks

**Comment by ibrierley** [comment]
Could you put a working (bar the erro) jsfiddle that will easily show the error ?

**Comment by ylerjen** [comment]
Here it is : http://jsfiddle.net/vsupdg5s/

Note that this fiddle will not work because loading an SVG from my domain in jsFiddle will throw a CrossDomain exception, but if you copy the javascript locally and load your own svg, it should do the trick (I tested it).
The jsFiddle's HTML tab is the content of my svg file if you want to test exactly my file.

**Comment by ibrierley** [comment]
Can you clarify the problem and error, I get a has_cloned message and the url, I don't get any failed to construct URL. Looking at http://svg.dabbles.info/git390.html

**Comment by ibrierley** [comment]
ah ignore me, cache wasn't updated to right version

**Comment by ibrierley** [comment]
Ok, http://svg.dabbles.info/git390.html  I think will work...
I think URL needs to be renamed to Snap.url everywhere in snap.svg.js.
Amended copy at http://svg.dabbles.info/snap.svg4test.js

I'm not sure if this is correct, so not submitting as a patch as yet, but see if it helps.

Is it possible browsers are just viewing funcs with capitals as constructors (not a js expert so not sure if thats correct or not) ?

**Comment by ylerjen** [comment]
This one is ok for me, it's working. Thanks for your reply :+1: 

I would say that the browser takes it equally if its a PascalCase or a camelCase function name. 
But yes, it'seems that the called URL() function is the one from the [JS web API Interface](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) but not the one overriden by Snap...

**Comment by superbiche** [comment]
@ylerjen could you please make a PR with your fix? It solved the issue in my case.

**Comment by ylerjen** [comment]
@superbiche Sorry for the late response. The PR has been made (#501). But I can't say if this will be merged soon as the repo seems to not be maintened anymore...
