### ISSUE TITLE
Transform matrix rounding

### ISSUE THREAD

**Issue by jvail** [adobe-webplatform/Snap.svg#393]
I am confused why using the API like here ..
```javascript
g.transform(Snap.matrix(a, 0, 0, a, dx, dy).toTransformString());
```
.. and here ..
```javascript
g.attr({
  'transform': 'matrix('+ a  + ' 0 0 ' + a + '  ' + dx + ' ' + dy + ')'
});
```
.. gives a different result than using svg directly ... (which behaves as intended/expected)
```javascript
 $(g.node).attr({
  'transform': 'matrix('+ a  + ' 0 0 ' + a + '  ' + dx + ' ' + dy + ')'
});
```
Translating seems to work well but combined with scaling (a > 0) the transformation does not work correctly in example 1&2 if I apply several transformations one after the other (panning & zooming).

Thank you
Jan

**Comment by ibrierley** [comment]
Could you put the testing example with values on a jsfiddle or similar

**Comment by jvail** [comment]
It is a rounding error: I am using an svg overlay on a map and have svg coords in projected coordinates (large and long numbers). After panning and zooming a few times the shapes where not in place anymore.

I looked at the transformation strings of all examples above and it turned out that floats are striped at 4 decimal places in the matrix<->string conversion. In a brute force attempt I simply replaced .toFixed(4) with .toFixed(20) everywhere. That fixed the problem... I am not sure where exactly the crucial rounding takes place, therefore I can not supply a bug fix - however, would be nice if that could be fixed.

Thank you
Jan

**Comment by ThomasBrierley** [comment]
This is a duplicate of #378 and is fixed by #379 but has not yet been merged.

The issue is with exponential notation parsing. You will notice it on numbers less than 1x10^-6 or greater than 1x10^20 which JavaScript will output with e notation when converting to a string.

I would suggest rolling back to v0.4.0 until a new release.

**Comment by jvail** [comment]
I tried it with 0.4.0 but I get the same result:

* 1
```javascript
 g1.attr({
   'transform': 'matrix('+ a  + ' 0 0 ' + a + ' ' + dx + ' ' + dy + ')'
 });
```
gives a rounded result
```xml
<g transform="matrix(0.4186,0,0,0.4186,-529859.3747,2574970.725)">
  <path d="..."></path>
</g>
```
* 2
```javascript
$(g2.node).attr({
 'transform': 'matrix('+ a  + ' 0 0 ' + a + ' ' + dx + ' ' + dy + ')'
});
```
correct 
```xml
<g transform="matrix(0.4186452654937383 0 0 0.4186452654937383 -529859.3747375201 2574970.725011102)">
  <path d="..."></path>
</g>
```

**Comment by ThomasBrierley** [comment]
Sorry i misinterpreted your post, this isn't a duplicate.

So to clarify... your issue is with reduced transform precision. Precision *may* be limited for a good reason. Unlike natively setting the attribute, Snap combines transform commands into a matrix, and in the matrix.js source ```toFixed(4)``` appears to have been intentionally used on input. We should try to find out why before assuming it's unnecessary or incorrect.

I can think of two cases where this could cause an issue with events:

1. Using a viewBox, width, height combination causing SVG units to be larger than event units by a factor of 10000. This would cause a loss of event coordinate precision when applied to SVG elements.

2. Using SVG element transforms to cumulatively store event coordinate state. This could cause a *more* noticeable cumulative error between event and element displacement.

Do either of these apply to your use case?

**Comment by jvail** [comment]
Yes, you are right. Most likely the rounding is applied for a good reason. I just expected the library to behave in the same way as the browser svg api does - that was confusing. I guess the second case applies.

Thank you 
Jan

**Comment by ThomasBrierley** [comment]
It is possible to implement gestures that do not accumulate error, and I encourage you to do so - not because of this limitation with Snap, but because you will create more robust gestures which are independent of precision.

Cumulative error is caused by using incremental deltas between current and previous move events. To avoid this, compare each move event to the start event. You will need to store at least two variables for the duration of the gesture.

1. The start event(s) position.
2. The start element transform.

Panning gesture pseudo code:
(vector and matrix types and operators for brevity)
```
// Event Transform
translate = (movePos - startPos);

// Element Transform
moveMatrix = startMatrix + translate;
```

Pinch zoom gesture pseudo code:
(vector and matrix types and operators for brevity)
```
// Event Transform
translate = ( movePosA - startPosA + movePosB - startPosB ) / 2;
scale = || movePosA - movePosB || / || startPosA - startPosB ||;

// Element Transform
moveMatrix = startMatrix + translate + scale;
```

For any given move event the number of operators between the start values and calculated values are constant, which means there is a constant rounding error. Now all you have to worry about is the sub-pixel precision of the SVG matrix, and 4 decimal places is more than enough.

Hope that helps :)

**Comment by jvail** [comment]
Thomas, thank you. I'll give it a try. Jan
