### ISSUE TITLE
event.currentTarget is null on drag.onmove and drag.onend

### ISSUE THREAD

**Issue by binishkaspar** [adobe-webplatform/Snap.svg#416]
event.currentTarget is null on drag.onmove and drag.onend

https://github.com/adobe-webplatform/Snap.svg/blob/master/src/mouse.js#L433

In the above line, may be changing `Snap.mousemove` to `el.mousemove` will fix the problem.

**Comment by ibrierley** [comment]
Could you provide a jsfiddle ?

**Comment by binishkaspar** [comment]
Please check this http://jsfiddle.net/suuzdmq7/5/  - here you can see the currentTarget is not correct on drag event, its working as expected in click event.

**Comment by ibrierley** [comment]
On the example, you have the parameters wrong. 

eg...  http://jsfiddle.net/suuzdmq7/10/

```
block.drag(function(dx,dy,x,y,evnt,ss){
 console.log( this )
 this.attr({ fill: 'red' });
 console.log('On Drag Move', dx,dy,x,y,evnt.target.toString());
}, function(x,y,evnt){
 console.log( this );
 console.log('On Drag Start', x,y,evnt.target.toString());
}, function(evnt){
 this.attr({ fill: 'blue' })
 console.log('On Drag End', evnt.target.toString());
});
```

Couple of extra thoughts...

Normally you wouldn't use the evnt param, you would use 'this' which refers to the Snap element, and deal with that. There are certainly some times you want the event itself, but normally not to refer to the target.

Be careful dumping out evnt.currentTarget or similar, try evnt.currentTarget.toString() if its null, as the reference may have got overwritten since the console, as this will convert to string value rather than reference that can change.

Now, looking at currentTarget vs target on the event, its document vs rect, which surprised me, this may be correct though as they aren't the same, but it would need further clarification. Either way, you can get around it by using 'this' (and if necessary this.node to reference the DOM element).

**Comment by binishkaspar** [comment]
Brilliant. Thank you so much the detail explanation and best practice. Using `this` solves the problem.  

Unfortunately we can't use target, because it dose not provides the currentTarget element - you can see it here http://jsfiddle.net/suuzdmq7/12/ when you drag the box above other box, target value changes. And that's the expected behaviour of target property in event object.  But i expected the currentTarget object, anyhow the problem is solved by using `this`.
