### ISSUE TITLE
Is snap.svg dead?

### ISSUE THREAD

**Issue by thewolf** [adobe-webplatform/Snap.svg#427]
160+ issues and the last source change 9 months ago! is this project still maintained? 

also how does it compare to svgjs?

**Comment by philippfrenzel** [comment]
Hi, looks like the last commit in the dev branch was in August - so like 4 months ago ...

**Comment by ThomasBrierley** [comment]
It's not "dead", but development is "dormant". Lots of people use Snap and have been continually contributing to bug reports and fixes, so it's alive, just in need of a little attention.

I think the inactivity is due to Snap being largely the work of one individual, Dmitry, who also appears to be the sole maintainer. It's understandable that one person has other commitments and it must be difficult to find others who are familiar enough with the code to help in that role.

The vast majority of issues aren't bugs, i know this because i've gone through most of them hunting for interesting things to debug. Many new users ask question through issues and @ibrierley pretty much single handedly addresses them all, they just need to be closed.

I do think allowing some volunteers to help manage the issues would trim them down significantly to give a more realistic representation of actual issues at a glance.

**Comment by ibrierley** [comment]
I suspect this will get closed before long, so in that respect I would say like Thomas its dormant just at the moment whilst Dmitry is busy, but a quick few thoughts.

Snap is pretty stable I find, I think there's a memory loss fix from Thomas I would like to see included, but a lot of the other 'issues' aren't really issues, or are just Snap questions etc, or could be worked around relatively easy.

SVGJS I won't comment on much apart from saying its active, similar like most libraries, its primarily one person, so similar things can always happen when real life gets in the way :). I think its a little behind with animation, but thats being worked on,

I would say, to try and find the right tool for the job though, even within the few SVG libs, there are a few things some are better at than others, and sometimes you can get an idea by looking through the docs. One may have more methods for animation, another for positioning text.

With the advent of Chrome messages saying SMIL is being deprecated (altho I think there is a js replacement) I think good SVG libs will remain important.

If you need performance with animation, I would take a look at combining Velocity with Snap, or possibly CSS with Snap (although check IE support for what you need).

So turning it around, rather than asking if a project is active (still a fair question), say what you would like the project to do, maybe someone has already got a plugin or a solution for that.

One thing I think it would be good to do some time is maybe start a github for Snap plugins, and have a bunch of common plugins there, as I assume its a balance between wanting to include lots of solutions to problems and bloat up the main codebase, when a plugin would work.

**Comment by thewolf** [comment]
fair enough, I'll give snapsvg a shot :)

**Comment by tonkonogov** [comment]
A quick think about the sole maintainer. I think it can't be resolved by adding one more new person in order to handle all of the pull requests. The main concern behind it is this [page](http://snapsvg.io/contributions/), which should be filled before any request. As I understand, that enterprise stuff and preoccupation with another project (see #424) are the key reason for this dead-like status of the project
Nevertheless, I have been already using Snap for more than half a year and I find it stable and ready for production usage. And thankfully I haven't faced with that infamous memory leak bug.

**Comment by runninghead** [comment]
A pdf or html page to help new users find, install and use Snap would be great! There’s links all over the web to it but I’ve encountered broken links everywhere now, even on Adobes Extensions site. Any advice? I just really really want a free, simple to use, svg wysiwyg animation editor (just for making simple graphics move).

**Comment by ibrierley** [comment]
There is the main snap home page, which has a Youtube video, intro and all the docs there. Also some stuff at http://svg.dabbles.info/
