### ISSUE TITLE
getBBox() not working consistently

### ISSUE THREAD

**Issue by SocVi100** [adobe-webplatform/Snap.svg#434]
The getBBox() function of Snap is really awesome as it does what the browsers should have done when they implemented getBoundingClientRect(), but it's behaving extrangely when it comes to do it's work with groups. That is:

`<ellipse id="elli" cx="200" cy="200" rx="100" ry="50" stroke="black" fill="none" transform="rotate(30, 200, 200)"></ellipse>`

I use getBBox() on it and everything is allright:

  var elli = paper.select('#elli');
  var box = elli.getBBox();
  d.rect(box.x, box.y, box.width, box.height).attr({stroke: 'red', fill: 'none'});

after this code the red box appears completly stick to the rotated ellipse, but if I change the markup to this:

`<g id="elli" transform="rotate(30, 200, 200)">
    <ellipse cx="200" cy="200" rx="100" ry="50" stroke="black" fill="none"></ellipse>
</g>`

then the red box behaves as it was surrounding the BoundingClientRect, that is bigger than the ellipse, so the red box sides are separated from the ellipse.

Is this a bug or is it the intended behaviour? I need to get the boundings of a set of figures inside a group and I can't manage to do now.

**Comment by ibrierley** [comment]
This is correct behaviour in a way, in terms of its down to browser bug/feature/interpretation as opposed to Snap.

You will probably find it works ok in Firefox but not in Chrome. Eg take a look at https://jsfiddle.net/ian_b/6w9vy6e7/3/ in both.

Also look at the console...you will see that the native getBBox is the same as the Snap getBBox. No surprises I guess as I think Snap calls the native browser getBBox for its info.

So whatever, I would consider it unreliable to use a bounding box in a group of rotate elements, due to browser differences, and I would consider it unlikely Snap will be coded around that in the near future or at all due to that, but as ever I may be wrong! Ie, whatever solution you are looking for, if behind the scenes it uses getBBox() it will have problems.

getBoundingClientRect and getBBox are supposed to be different, and take into account different coordinate spaces (wasn't sure if there was some confusing there, there often is by me!).

**Comment by SocVi100** [comment]
Sorry, my example was wrong (I've edited it). What I meant was that is doesn't give the same result to get the BBox of an element with rotation applied, than getting it from a group with only this element and the rotation applied to the group...
Now the examples are corrected and elli.getBBox() SHOULD give the same result in both cases, but it doesn't.

**Comment by ibrierley** [comment]
Yep, but does the native el.node.getBBox() return the same as Snaps el.getBBox() ?

**Comment by SocVi100** [comment]
Maybe I haven't described the issue correctly or we are not understanding each other.
I've prepared a CodePen to clarify the issue. Please, see it here:

[CodePen Example](http://codepen.io/Vi100/pen/GoOqPq)

The correct behaviour SHOULD be that the two red boxes were equal, like in case 1. Isn't it?
