### ISSUE TITLE
Does Snap work via modifying SMIL?

### ISSUE THREAD

**Issue by corysimmons** [adobe-webplatform/Snap.svg#439]
Didn't want to dig through source code and didn't see anything on the site for it. Just curious because SMIL animations are deprecated (bummer).

**Comment by ibrierley** [comment]
No, it works via requestAnimationframe and directly modifying attributes.

**Comment by ThomasBrierley** [comment]
Yeah Snap wasn't designed for this but I think declarative animations for SVG are useful. My guess is SMIL was depreciated in favour of creating a more unified Web Animation API which should include declarative animations that you can apply to SVG content.

Checkout this polyfill: https://github.com/web-animations/web-animations-js

I haven't tried it yet, would be interested to know how you get on.

**Comment by corysimmons** [comment]
@ibrierley Cool, I'll give it a shot then! :D

@ThomasBrierley The Web Animations spec is just the conversion of CSS animations to JS?

**Comment by ThomasBrierley** [comment]
Yeah sort of, it's an attempt to unify existing separate animation methods:

https://w3c.github.io/web-animations/#use-cases

So it should provide declarative animation to more than HTML DOM, and a way
to define and modify declarative animations in JavaScript. Although keep in
mind it's still in the draft stage.

This sort of thing is hard to do in Snap for instance because once you
start an ```animate``` you cannot modify values without stopping it and
breaking the ease. You can achieve this instead by setting up your own
loops, taking care of the easing yourself and only using Snap to interface
with the SVG, in some cases I've even removed Snap completely for
performance reasons.

The point being that once you set up your own loop you have access to the
variables being transitioned and you can modify them on the fly... this is
what the Web Animation API could make a lot easier because it takes care of
the loop and optimises it, yet still lets you modify all the parameters
while it's playing... at least that is my limited understanding of it.

**Comment by ThomasBrierley** [comment]
Yeah sort of, it's an attempt to unify existing separate animation specifications including CSS animations:

https://w3c.github.io/web-animations/#use-cases

So it should provide declarative animation to more than HTML DOM, and a way to define and modify declarative animations in JavaScript. Although keep in mind it's still in the draft stage.

This sort of thing is hard to do in Snap for instance because once you start an ```animate``` you cannot modify values without stopping it and breaking the ease. You can achieve this instead by setting up your own loops, taking care of the easing yourself and only using Snap to interface with the SVG, in some cases I've even removed Snap completely for performance reasons.

The point being that once you set up your own loop you have access to the variables being transitioned and you can modify them on the fly... this is what the Web Animation API could make a lot easier because it takes care of the loop and optimises it, yet still lets you modify all the parameters while it's playing... at least that is my limited understanding of it.

**Comment by corysimmons** [comment]
@ThomasBrierley Thanks for the explanation. Sounds pretty neat. I guess I'll learn that instead. :)
