### ISSUE TITLE
Documentation is not helpful

### ISSUE THREAD

**Issue by thednp** [adobe-webplatform/Snap.svg#440]
I need to know how utility functions such as `isBBoxIntersect`, `getSubpath` and `intersection` work, many of the methods are poorly documented.

Is this project still alive?

**Comment by ibrierley** [comment]
The project isn't very active by the author atm, but there is normally decent support from here, or SO etc.
Documentation for the first two seems reasonable and intuitive by the respective names in the docs.

isBBoxIntersect is pretty self explanatory, give it two bboxes and it will return true or false.

getSubPath will return a smaller path given two lengths into the path being segmented.

intersection returns the cross points of two paths. Note, it may cross at several points, which is why the returned structure will not be too obvious, but x,y will be the main values wanted. The other values in the return object can be a bit fiddly to understand, but iirc it will contain the path segments of the intersection (which I think is low level for what most people want, but if there's a specific example posted I'll try and help with).

If you are struggling with one of them, I would put up a jsfiddle highlighting the problem, I'm sure someone will try and help.

**Comment by thednp** [comment]
Thanks for your input. I understand most of those are self explanatory, but a code without examples is redundant more or less, especially for a topic that's so hot.
