### ISSUE TITLE
Paper.clear() also clear defs, which it shouldn't

### ISSUE THREAD

**Issue by atorger** [adobe-webplatform/Snap.svg#453]
The documentation states that Paper.clear() should not clear defs (which is good as you may have gradients etc set up there), but in actuality it does clear defs as well leaving an completely empty svg.

I'm using snapsvg 0.4.1

As I'm using jquery my workaround was:
$("#svg").children().not('defs').remove();
And that is the behavior I expect from Paper.clear()

**Comment by ibrierley** [comment]
Could you put a jsfiddle up ?

**Comment by atorger** [comment]
https://jsfiddle.net/jgmn2jr5/

There you go. The "s.clear();" line should make no difference as it shouldn't remove defs, but it does. Run the code with the line commented out -- works. Apply it, doesn't work

**Comment by ThomasBrierley** [comment]
> Paper.clear()
> Removes all child nodes of the paper, except \<defs\>.

This is a little ambiguous, as you have discovered it _does not_ remove the ```<defs>``` node, but it _does_ remove all of it's children, so this is not a bug. I think the intention is to be able to expect the ```<defs>``` node to always exist so it can be appended to without checking for it's existence every time.

If you are after a generic one liner for clearing everything in an SVG excluding the ```<defs>``` node _and_ it's children, you can use the not operator in a query selector like so:

```Paper.selectAll('SVG > *:not(defs)').remove()```

**Comment by atorger** [comment]
Ok fair enough, closing this. I saw on stackoverflow that others have had the same issue with the same misconception, so I think the documentation should be clarified, perhaps adding in that oneliner for us that need the other behaviour.

In my case I have empty svgs in my HTML but with the defs set up with stuff like gradients and blurs which I then use in the snap code. Those SVGs are re-rendered from scratch to adapt to various layout adjustments, and then clearing them but keeping defs intact is logical.

**Comment by ThomasBrierley** [comment]
@atorger 

I think there is a better solution for your use case: Load the defs and your content into separate in-line SVGs. In-line SVGs share defs and ids with each other for the entire HTML frame, so your references will work in exactly the same way. The defs SVG doesn't need to be visible just present somewhere in the DOM.

It's good to understand this because it also means polluting the global in-line SVG scope is very easy, declarative SVG references such as ```filter="url(#blur)"``` are absolute and cannot be given context like query selectors... in fact references aren't even assumed to be under a defs node.

**Comment by atorger** [comment]
Thanks for that tip, I'll look into doing it like that.
