### ISSUE TITLE
Proposal add api, demo and guide to devdocs

### ISSUE THREAD

**Issue by brutalcrozt** [adobe-webplatform/Snap.svg#454]
This is the requirement from devdocs :
- [x] Source code documentations only (HTML format)
- [ ] Project must be open source (as defined by OSI) and actively maintained
- [x] License must permit alteration, redistribution and commercial use
- [x] Project must have >3k stars on GitHub or equivalent

i just watch Dmitry Baranovskiy's [talk](https://www.youtube.com/watch?v=SeLOt_BRAqc&spfreload=10) then thinks bloody scary things when people not learn SVG.

if you are agree and guide / lead me a little bit. I will aiming to escape the voting system, if all that check list is checked hopefully it can be on offline mode in 7 days at least. :smile:

**Comment by ThomasBrierley** [comment]
> i just watch Dmitry Baranovskiy's talk then thinks bloody scary things when people not learn SVG.

I know right... I learned SVG, I even read the specs, including the unimplemented parts, and I still keep my nunchucks close by. Just hope no one ever asks me to explain the arc command.

Devdocs.io looks like a great idea, I do hope Snap.svg can make it on there. It would probably help improve the docs through better exposure.

- The docs are in HTML format, I think they might be generated by jsdoc.

- The licence is "Apache 2" which should satisfy No.3.

Beyond that we probably need Dmitry's input.

**Comment by brutalcrozt** [comment]
> Beyond that we probably need Dmitry's input.

yes , we need that. I also notice that on
[MDN Doc for SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Tools_for_SVG) also [W3C SVG implementation](https://www.w3.org/Graphics/SVG/WG/wiki/Implementations) list Raphaeljs, what about SNAP ?

**Comment by ThomasBrierley** [comment]
I've added Snap.svg to the MDN "[Tools for SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Tools_for_SVG)" doc.

I think the Snap docs could do with linking to native SVG references too, (this would work nicely in devdocs), because the vast majority of bugs submitted here are misconceptions from new users to Snap and SVG who don't know where the separation of Snap and SVG are.

Snap is more of a normalisation layer like jQuery than a polyfil, but because people don't really start out knowing native SVG they don't get that some stuff just doesn't work because the browser implementations are very buggy or there is no support at all regardless of normalisation.
