### ISSUE TITLE
Change FILL attr on Illustrator SVG not working on IE Edge

### ISSUE THREAD

**Issue by kikemx78** [adobe-webplatform/Snap.svg#457]
This code should append an SVG created on Illustrator and change each `<path>`'s color. Works OK on Chrome & Firefox but not on IExplorer Edge.

`var jerseyColor1 = "#DD2C00";
Snap.load('img/jersey.svg', function(f){
    g = f.select("g");
    for ( var i = 0; i <3 ; i++ ){
      f.select("path[fill='#3F6DB5']").attr({fill: jerseyColor1 });
    }
    s.append(g);
  });`

Console's Error: SCRIPT5007: Unable to get property 'attr' of undefined or null reference

**Comment by ThomasBrierley** [comment]
Snap supports SVG, not Illustrator specifically (which until Dmitry recently re-wrote - had a subpar SVG exporter).

No one can debug this without the SVG source. You could either post an example with the whole source as a jsfiddle or reduce the SVG down to the offending nodes - at which point you will probably be able to deduce for yourself if it's an SVG XML issue, a Browser bug or a Snap bug.

Tip: If available use a "plain SVG" export option... various illustration packages tend to embed extra data to prevent information loss, often into their own namespace or even in a non-XML friendly way which will break certain SVG renders (especially IE).

**Comment by kikemx78** [comment]
Hello ThomasBrierley, heres a link to a plunkr:

 [https://embed.plnkr.co/tztomHcPRsXtNaRVGTlC/](url)

Firefox, Opera & Chrome versions work ok. 

What do you mean by "plain SVG" export option?

**Comment by ThomasBrierley** [comment]
Looks like you are using the latest version of Illustrator and the SVG source is obscenely clean :smiley: so that's not the issue. I hadn't seen a sample output from the new exporter before, nice job @DmitryBaranovskiy ! most legible generated SVG XML I've ever seen.

I haven't got an MSIE VM at hand, however on closer inspection my instinct is the query selector in your code: ```path[fill='#3F6DB5']```. I vaguely remember there being a quirk in MSIE where the DOM API for setting SVG fill "helpfully" normalises the hex value format to lower-case.

If I'm right you might be able to use lower-case A-F in your hex values to solve it... A better solution however is probably not to select paths by fill values, as this introduces an additional temporal context which is less flexible and hard to debug. One possible alternative is to use classes.

**Comment by kikemx78** [comment]
@ThomasBrierley, you're right. Changing hex value's format to lower-case solves the issue on IExplorer and not affecting FFox or Chrome's performance.

Thanx a lot!
