### ISSUE TITLE
Set.animate doesn't work with radius r for circles.

### ISSUE THREAD

**Issue by SpazzMarticus** [adobe-webplatform/Snap.svg#464]
I tinkered around with Snap.svg [0.4.1] and tried to animate two circles a once, but the animation does only apply to the `r`-attribute of the set `<g r="100">`, not the circles `<circle r="100">` themself.

Example: https://jsfiddle.net/ym239LwL/

Is there a fix for that?

**Comment by ThomasBrierley** [comment]
The problem is not with Snap or SVG, there are multiple misconceptions in your example about how SVG groups _work_ and what Snap sets _are_.

## SVG Groups

SVG groups only support global attributes e.g ```fill```. So before even looking at programmatically creating and manipulating SVG nodes, look at this static example that sums up your issue:

``` SVG
<svg viewBox="-5 -5 10 10">
    <g r="5">
        <circle />
    </g>
</svg>
```
The circle's computed ```r``` value will be 0. The SVG parser effectively ignores the r attribute all together because it's not an inheritable attribute, ```r``` should be defined on the circle itself.

## Snap Sets

Snap sets !== SVG groups. A group (```<g></g>```) is just another element in the DOM, a set is just an arbitrary collection of elements that only exists in JavaScript regardless of their relationship in the DOM. What you want to do is obtain a set of elements (the circles) then operate on them directly together:

Using only a selector:

```var mySet = Snap.selectAll('svg g > circle');```

Or using existing parent element references for greater specificity:

```var mySet = myGroup.selectAll('> circle');```

Or seeing as you already have references to the original elements just create a new set directly:

```var mySet = Snap([circle1, circle2, circle3]);```

See http://snapsvg.io/docs/#Snap for details.

**Comment by SpazzMarticus** [comment]
Okay, I got group and set mixed up.

https://jsfiddle.net/ym239LwL/2/

Works fine now!
