### ISSUE TITLE
Can't use a single element to clip multiple things

### ISSUE THREAD

**Issue by mhelvens** [adobe-webplatform/Snap.svg#471]
If I use an element as clip-path (or mask) for more than one object, I would expect a single `<clippath>` to be created in `<defs>`, as always, and have those objects to use the same id. Instead, it seems a `<clippath>` is created for each _use_, but all but the last will be empty, so they won't work.

[jsfiddle](https://jsfiddle.net/mhelvens/16nqbc18/)

I know that the things to be clipped could be put in a single group, but this is not always possible or desirable.

**Comment by ibrierley** [comment]
Probably best putting some code up highlighting the problem so it's easy to recreate on a jsfiddle or similar.

**Comment by mhelvens** [comment]
Fair enough. I added a jsfiddle link.

**Comment by ThomasBrierley** [comment]
Ha, weird, the second steals the content of the first.

Without reading the code: Let say Snap coerces the element reference into a ```clipPath``` by wrapping it in one, splicing it into the ```<defs>```, and adding the ```URL``` to ```attr()```'s target(s)... Your local reference still points to the original element inside the new clipPath, _not_ the new clipPath itself.

I would prefer explicit clipPath creation instead of coercion, but seeing as the former doesn't exist via Snap (AFAIK) I guess we can fix this by adding a check to bubble up the parent nodes until it hits a ```clipPath``` or ```body``` element before doing any coercion.

Although this is a bit inefficient, and has some edge cases without objective behaviour, for instance: what should happen when you pass it a subset of an existing clipPath?
