### ISSUE TITLE
animate the fill use the color of rgba, it will be the color of hex

### ISSUE THREAD

**Issue by imfenghuang** [adobe-webplatform/Snap.svg#492]
demo http://codepen.io/anon/pen/YpmgOJ

when I use hover to change the text's fill color, the first line text I also use the fill-opacity to control the opacity, it is working fine.

the second line I use the rgba color, when the text animate, the fill color become the hex color

Am I wrong?

**Comment by DavidBruchmann** [comment]
I love it, you're checking systematically the weak points ;-)
Seemingly another fault of snap.svg.
You still have the option to animate color and opaque separated, but snap.svg shouldn't change your values I think. But perhaps there is a reason that it's translated in hex-values ...

**Comment by DavidBruchmann** [comment]
I changed your codepen a bit, so that the colors are the same and opacity is set in both lines, furthermore I included the dev-version instead of master:
http://codepen.io/dbruchmann/pen/ObKexq
but the second line changes the color different. Don't know in the moment how to track the calculated keyframes.
The difference is then only between rgb and rgba and the missing attribute  fill-opacity="0.1" in the second line.
Probably colors will change the same if rgb and rgba are accepted and not changed to hex.

@DmitryBaranovskiy is there any reason that snap.svg is converting the colors?

**Comment by DmitryBaranovskiy** [comment]
Fixed on `dev`.

**Comment by DavidBruchmann** [comment]
Thanks!

**Comment by imfenghuang** [comment]
nice
thanks @DavidBruchmann @DmitryBaranovskiy
