### ISSUE TITLE
How i can use rotate for <path>?

### ISSUE THREAD

**Issue by semiromid** [adobe-webplatform/Snap.svg#536]
if  `path` was on the coordinates X 100 and Y100
and next steps:
1. Step  - use `transform="translate(200,200)" ` on  X200 and Y200
2. Step - use  'rotate(180 200 , 200)'

result - rotate will be problematic work. Rotate will be use coordinates X 100 Y100 instead X 200 and Y200

**Comment by ibrierley** [comment]
Can you put a jsfiddle up ?

**Comment by semiromid** [comment]
Variable script:
`$zahvat_1` - rotate problematic worked. Bad worked.
`$prm_2` - rotate is good. No problem. Good Worked.

https://jsfiddle.net/vzmy375d/4/

**Comment by ibrierley** [comment]
I 'think' your problem is that you aren't including the previous transform in the new transform that you want to animate to. So as soon as you set it, the old one will get overwritten.

You can use the old transform with element.transform(), so

$zahvat_1.animate({transform: $zahvat_1.transform() + 'r360,100,100' }, 1000, mina.bounce);

https://jsfiddle.net/vzmy375d/5/

**Comment by semiromid** [comment]
Thanks You!) Worked Good! I love You !!!)


https://jsfiddle.net/vzmy375d/8/
