### ISSUE TITLE
Two questions about path.js 

### ISSUE THREAD

**Issue by nblthree** [adobe-webplatform/Snap.svg#645]
I would like to know what this function does https://github.com/adobe-webplatform/Snap.svg/blob/master/src/path.js#L219-L237 and what are the `Tvalues` and `Cvalues` and how did you get them?

**Comment by ibrierley** [comment]
Good question, in the absence of a reply from Dmitry for the mo, it looks related to this code here (at the bottom)...and them being Legendre-Gauss weights ? I can't pretend to understand that stuff though! Just trying to head you in the right direction.

http://processingjs.nihongoresources.com/bezierinfo/sketchsource.php?sketch=cubicGaussQuadrature at

**Comment by ibrierley** [comment]
I'm not sure I should ask though, why do you want to know ? :D

**Comment by nblthree** [comment]
@ibrierley just trying my luck on making the calculation more precise. 

https://github.com/bpmn-io/path-intersection/issues/17

**Comment by ibrierley** [comment]
Maybe if you go to https://pomax.github.io/bezierinfo/legendre-gauss.html#n18  and rather than select n = 12 (the one Snap uses), try n = 32 for example and copy the values for wi and xi eg at https://pomax.github.io/bezierinfo/legendre-gauss.html#n32   and then change the n value in the function to 32. 

I think Tvalues are abscissa and Cvalues anre weight...maybe 
Just guessing!

**Comment by ibrierley** [comment]
Or there's a function at the top of that page, and rewrite for js (there's probably solutions out there already though).

**Comment by nblthree** [comment]
@ibrierley thanks you are right the problem occurs only in the other library
